In [3]:
import numpy as np
import pandas
from sklearn import datasets

print(np.__version__)
print(pandas.__version__ ) ##double underscore

## Start by pulling in a dataset?

digits = datasets.load_digits()

X = digits['data']   # this is the data with each 8x8 image "flattened" into a length-64 vector.
Y = digits['target'] # these are the labels (0-9).

1.16.4
0.24.2

NameError: name 'col' is not defined

In [5]:
## exploring the data set:

print("The shape of Y is:", Y.shape,"; it only has the 1 dimension")  ## see the dimensions?
print("The shape of X is:", X.shape,"; it has 2 dimensions")
print("There are ",X.shape[0],"; images in the data set")
print("and each image has ",X.shape[1]," pixels")

The shape of Y is: (1797,) ; it only has the 1 dimension
The shape of X is: (1797, 64) ; it has 2 dimensions
There are  1797 ; images in the data set
and each image has  64  pixels

## What is happening?

X is an *object* in Python.  It has attributes that we can acces by adding a . and the name of the function. (This is an example of Object Oriented Programming (OOP).  

This object is a numpy.array, and we can look at the stuff inside of it with [square brackets].  
When I'm looking at a function (like shape) I call on its variables with (round brackets).  This is an important distinction!

In [8]:
#If I want to look at a single record or row of X, I type:

n = 6 ## change me!

print(X[n])  #this is the nth X

#To see the corresponding Y, we type:
print(Y[n])

[ 0.  0.  0. 12. 13.  0.  0.  0.  0.  0.  5. 16.  8.  0.  0.  0.  0.  0.
 13. 16.  3.  0.  0.  0.  0.  0. 14. 13.  0.  0.  0.  0.  0.  0. 15. 12.
  7.  2.  0.  0.  0.  0. 13. 16. 13. 16.  3.  0.  0.  0.  7. 16. 11. 15.
  8.  0.  0.  0.  1.  9. 15. 11.  3.  0.]
6

In [11]:
##We've set this up so that the name is X, but the name could be anything:

num_set= X  ## I like to give things my name, because I'm not creative

num_set[n]

array([ 0.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,  5., 16.,  8.,
        0.,  0.,  0.,  0.,  0., 13., 16.,  3.,  0.,  0.,  0.,  0.,  0.,
       14., 13.,  0.,  0.,  0.,  0.,  0.,  0., 15., 12.,  7.,  2.,  0.,
        0.,  0.,  0., 13., 16., 13., 16.,  3.,  0.,  0.,  0.,  7., 16.,
       11., 15.,  8.,  0.,  0.,  0.,  1.,  9., 15., 11.,  3.,  0.])

In [15]:
## If I want to see just the mth number in X, (a "feature"), I use:
m = 12
X[n,m]

## note that counting starts at 0, so if m = 12, it is the 11th number in the row
#X[1,5]

8.0

In [14]:
## what if I want to see a specific column?

print(X[:,m]) ## list of Column m

## I wonder if I can get the answer from the previous box?

print(X[:,m][n]) ##  Why :,?  It shows that i'm looking at the 2nd dimension

##or:

print(X[n][m])

[10. 16. 15. ...  8. 16.  6.]
8.0
8.0

## Types

X (or amy) is an array -> basically a grid of numbers, and we can treat it as such.  But if we want to have columbs with other stuff, numbers, words, ect, we need something called a dataframe.  A dataframe is basically a spreadsheet.

In [16]:
##importing other datasets
##The first question is, where am I?  The os package lets us use command line type commands

import os

os.getcwd() 

## when I run this it tells me where on my computer we are

'S:\\Personal Folders\\2021_current\\AI_course_development\\Jupyter_4001'

In [4]:
## Nice!  I can look for my dataset.  
## I prefer relative folders, so starting where I am.  Make sure there is a folder called data!

survey = pandas.read_csv("data\Clean_Survey_2022-01-16.csv") 

##look at it!
survey

,Timestamp,program,Gender,Age,Height,Weight.,Old_Salary,Expected_Salary,Organization,Live_parents,...,Footsize,Alcohol,Tattoo,Sleep,Social_Network,Homework,Work,Travel,Tuition,Coffee
0,2019/02/04 11:26:35 am GMT-8,HRMG,Female,22.0,177.80,110.00,1400.0,4000.0,3. Non-profit or Government Agency,No,...,11.12000,0.0,Yes,8.00,10.0,10.0,0.0,Yes,No,0.00
1,2019/02/04 11:27:45 am GMT-8,HRMG,Female,24.0,175.00,63.00,2000.0,3750.0,2. Small Company,Yes,...,9.50000,0.0,Yes,8.00,7.0,20.0,0.0,Yes,Yes,2.00
2,2019/02/04 11:27:46 am GMT-8,HRMG,Male,24.0,182.88,100.00,2000.0,3500.0,2. Small Company,Yes,...,10.50000,1.0,No,6.00,20.0,20.0,8.0,Yes,No,0.00
3,2019/02/04 11:29:06 am GMT-8,HRMG,Female,34.0,NaN,61.30,2500.0,3500.0,1. Large Corporation,Yes,...,7.00000,0.0,Yes,78.00,14.0,20.0,0.0,Yes,No,1.00
4,2019/02/04 11:29:12 am GMT-8,HRMG,Female,24.0,160.00,54.00,0.0,3800.0,2. Small Company,Yes,...,8.00000,3.0,No,67.00,6.0,11.0,0.0,Yes,Yes,1.00
5,2019/02/04 11:29:30 am GMT-8,HRMG,Female,24.0,164.00,65.00,2500.0,5000.0,2. Small Company,Yes,...,9.25000,0.0,No,7.00,20.0,25.0,0.0,Yes,Yes,0.00
6,2019/02/04 11:29:38 am GMT-8,HRMG,Female,27.0,153.00,55.00,2300.0,3000.0,2. Small Company,No,...,6.00000,0.0,Yes,7.00,8.0,25.0,12.0,Yes,Yes,1.00
7,2019/02/04 11:31:56 am GMT-8,HRMG,Female,27.0,NaN,NaN,0.0,3500.0,2. Small Company,Yes,...,NaN,1.0,No,5.00,2.0,28.0,NaN,Yes,No,1.00
8,2019/02/04 11:33:25 am GMT-8,HRMG,Male,NaN,NaN,NaN,NaN,NaN,1. Large Corporation,No,...,NaN,NaN,Yes,NaN,NaN,NaN,NaN,Yes,No,1.00
9,2019/02/04 11:34:05 am GMT-8,HRMG,Male,40.0,185.00,90.00,2000.0,4000.0,1. Large Corporation,No,...,13.00000,0.0,Yes,7.00,3.0,14.0,0.0,Yes,No,3.00
10,2019/02/04 11:35:08 am GMT-8,HRMG,Male,25.0,165.00,70.30,1300.0,1600.0,1. Large Corporation,Yes,...,8.50000,0.0,No,7.00,4.0,12.0,3.5,Yes,Yes,0.25
11,2019/02/04 11:36:01 am GMT-8,HRMG,Female,25.0,163.00,52.00,NaN,NaN,1. Large Corporation,Yes,...,9.50000,0.0,No,6.00,20.0,20.0,8.0,Yes,No,2.00
12,2019/02/04 11:39:16 am GMT-8,HRMG,Female,38.0,NaN,60.00,3000.0,3500.0,3. Non-profit or Government Agency,No,...,9.00000,0.0,No,5.00,14.0,NaN,0.0,Yes,No,0.00
13,2019/02/04 11:40:00 am GMT-8,HRMG,Female,24.0,162.56,NaN,1920.0,NaN,3. Non-profit or Government Agency,Yes,...,9.75000,2.0,Yes,6.00,19.0,30.0,20.0,Yes,No,1.00
14,2019/02/04 11:42:54 am GMT-8,HRMG,Female,22.0,155.45,50.00,1600.0,2500.0,1. Large Corporation,No,...,9.50000,0.0,Yes,10.00,5.0,40.0,0.0,No,No,3.00
15,2019/02/04 11:44:47 am GMT-8,HRMG,Female,24.0,165.00,58.00,0.0,3000.0,1. Large Corporation,Yes,...,14.00000,0.0,No,7.00,25.0,40.0,8.0,Yes,No,1.00
16,2019/02/04 11:46:15 am GMT-8,HRMG,Male,23.0,179.00,86.00,2500.0,3200.0,2. Small Company,Yes,...,10.25000,5.0,No,7.00,2.0,24.0,8.0,No,Yes,3.00
17,2019/02/04 11:49:00 am GMT-8,HRMG,Female,22.0,158.00,53.00,900.0,4000.0,4. Other,Yes,...,9.25000,3.0,No,6.00,14.0,30.0,6.0,No,No,1.00
18,2019/02/04 11:49:12 am GMT-8,HRMG,Female,25.0,150.00,50.00,3500.0,4000.0,1. Large Corporation,Yes,...,9.00000,3.0,Yes,5.00,5.0,30.0,0.0,Yes,Yes,0.00
19,2019/02/04 2:31:07 pm GMT-8,HRMG,Male,25.0,178.00,75.00,4200.0,4000.0,1. Large Corporation,No,...,10.00000,3.0,No,6.00,13.0,NaN,0.0,Yes,Yes,4.00
20,2019/02/04 2:38:05 pm GMT-8,HRMG,Female,30.0,165.00,99.00,3000.0,5000.0,2. Small Company,No,...,10.20000,2.0,Yes,6.00,15.0,40.0,12.0,Yes,Yes,2.00
21,2019/02/04 2:40:15 pm GMT-8,HRMG,Female,25.0,170.00,114.00,2600.0,4000.0,2. Small Company,No,...,9.00000,NaN,Yes,7.50,14.0,24.0,NaN,Yes,No,1.00
22,2019/02/04 2:41:51 pm GMT-8,HRMG,Male,32.0,176.00,170.00,0.0,3000.0,1. Large Corporation,Yes,...,11.00000,1.0,No,5.00,3.0,5.0,14.0,Yes,No,2.00
23,2019/02/04 2:41:57 pm GMT-8,HRMG,Female,24.0,NaN,108.00,2800.0,4000.0,1. Large Corporation,No,...,6.50000,0.0,No,6.50,12.0,25.0,3.0,Yes,No,1.00
24,2019/02/04 2:44:01 pm GMT-8,HRMG,Female,22.0,170.18,506.00,0.0,0.0,1. Large Corporation,Yes,...,9.87525,1.0,Yes,6.00,10.0,8.0,0.0,No,No,NaN
25,2019/02/04 2:44:50 pm GMT-8,HRMG,Female,22.0,174.00,51.00,800.0,4000.0,1. Large Corporation,Yes,...,10.00000,3.0,No,8.00,14.0,20.0,12.0,Yes,No,1.00
26,2019/02/04 2:45:51 pm GMT-8,HRMG,Female,23.0,163.00,49.00,1700.0,3000.0,3. Non-profit or Government Agency,Yes,...,9.00000,0.0,Yes,6.00,2.0,10.0,4.0,Yes,No,1.00
27,2019/02/04 2:47:12 pm GMT-8,HRMG,Female,24.0,160.00,66.00,1600.0,3750.0,2. Small Company,Yes,...,9.50000,0.0,Yes,6.50,3.0,12.0,0.0,Yes,No,2.00
28,2019/02/04 2:47:32 pm GMT-8,HRMG,Female,23.0,157.00,66.00,2000.0,3750.0,1. Large Corporation,Yes,...,9.50000,0.0,Yes,6.50,NaN,30.0,0.0,Yes,Yes,1.00
29,2019/02/04 2:49:25 pm GMT-8,HRMG,Male,29.0,170.00,81.00,2400.0,4000.0,2. Small Company,No,...,10.56000,4.0,No,7.00,1.5,40.0,10.0,Yes,Yes,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,2020/09/14 8:39:29 pm GMT-7,BABI,Female,33.0,164.00,54.00,3833.0,NaN,1. Large Corporation,No,...,8.00000,0.0,No,8.00,10.0,10.0,40.0,No,Yes,1.00
110,2020/09/14 9:06:18 pm GMT-7,BMGT,Male,29.0,178.00,75.00,0.0,NaN,1. Large Corporation,Yes,...,9.00000,1.0,No,6.50,NaN,40.0,40.0,Yes,Yes,0.00
111,2020/09/15 11:40:49 am GMT-7,BABI,Female,41.0,166.00,78.00,4234.0,6500.0,3. Non-profit or Government Agency,No,...,9.80000,3.0,No,7.00,0.0,6.0,35.5,Yes,No,1.00
112,2020/09/16 7:02:41 pm GMT-7,BABI,Male,29.0,165.00,54.00,1800.0,3800.0,2. Small Company,Yes,...,10.00000,0.0,No,7.00,8.0,8.0,32.0,No,Yes,1.00
113,2020/09/19 9:04:56 pm GMT-7,BABI,Female,35.0,158.00,65.00,2000.0,5000.0,1. Large Corporation,No,...,6.50000,1.0,No,68.00,2.0,5.0,24.0,Yes,No,0.00
114,2020/09/22 1:24:16 pm GMT-7,BABI,Female,33.0,164.00,54.00,4042.0,4041.0,2. Small Company,No,...,7.50000,0.0,No,7.00,10.0,10.0,40.0,Yes,Yes,1.00
115,2020/09/22 7:29:14 pm GMT-7,BABI,Male,25.0,180.00,79.00,3900.0,4500.0,1. Large Corporation,No,...,10.00000,8.0,No,6.75,5.0,12.0,45.0,Yes,Yes,2.00
116,2020/09/23 9:31:22 pm GMT-7,BMGT,Male,24.0,170.00,73.00,2316.0,5000.0,2. Small Company,Yes,...,10.00000,0.0,Yes,5.00,1.0,40.0,40.0,Yes,Yes,4.00
117,2020/09/27 9:01:24 am GMT-7,BABI,Female,35.0,158.00,65.00,1500.0,3000.0,2. Small Company,No,...,6.00000,1.0,No,68.00,23.0,45.0,24.0,Yes,Yes,0.00
118,2020/09/28 10:46:56 am GMT-7,BABI,Male,40.0,183.00,86.00,6000.0,6500.0,1. Large Corporation,No,...,10.00000,0.0,No,6.00,1.0,25.0,20.0,Yes,Yes,1.00
119,2021/09/07 7:48:18 pm GMT-7,BABI,Male,22.0,178.00,75.00,5500.0,7000.0,1. Large Corporation,No,...,10.00000,1.0,No,7.50,8.0,3.0,40.0,No,Yes,2.00
120,2021/09/08 1:06:36 pm GMT-7,BABI,Female,48.0,155.00,48.00,NaN,NaN,2. Small Company,No,...,9.40000,3.0,No,7.00,0.0,NaN,NaN,Yes,Yes,1.00
121,2021/09/08 8:55:52 pm GMT-7,BABI,Male,26.0,181.00,96.00,4800.0,5500.0,3. Non-profit or Government Agency,Yes,...,11.00000,5.0,Yes,7.00,9.0,5.0,37.5,Yes,Yes,1.50
122,2021/09/09 3:31:49 pm GMT-7,BABI,Female,34.0,150.00,64.00,0.0,3000.0,2. Small Company,No,...,512.00000,0.0,No,8.00,10.0,3.0,0.0,Yes,No,1.00
123,2021/09/09 6:30:34 pm GMT-7,BABI,Male,24.0,172.00,165.00,4300.0,6000.0,1. Large Corporation,Yes,...,10.00000,1.0,No,6.00,8.0,6.0,45.0,Yes,Yes,1.00
124,2021/09/09 6:36:23 pm GMT-7,BABI,Male,28.0,175.00,148.00,0.0,8000.0,3. Non-profit or Government Agency,Yes,...,NaN,0.0,No,7.00,10.0,12.0,0.0,Yes,No,2.00
125,2021/09/09 7:55:05 pm GMT-7,BABI,Male,27.0,181.00,80.00,5000.0,7000.0,2. Small Company,No,...,11.00000,3.0,No,9.00,10.0,5.0,37.0,Yes,Yes,0.00
126,2021/09/11 12:23:18 pm GMT-7,BABI,Male,28.0,168.00,67.00,0.0,6666.0,1. Large Corporation,No,...,9.50000,2.0,No,6.00,6.0,4.0,45.0,Yes,Yes,2.00
127,2021/09/11 7:33:08 pm GMT-7,BABI,Female,34.0,152.00,47.00,4600.0,5400.0,3. Non-profit or Government Agency,Yes,...,8.75000,0.0,No,6.00,0.5,25.0,40.0,Yes,Yes,1.00
128,2021/09/13 2:42:47 pm GMT-7,BABI,Female,29.0,163.00,50.00,3500.0,4000.0,1. Large Corporation,No,...,8.75000,NaN,No,8.00,5.0,8.0,40.0,Yes,Yes,1.00
129,2021/09/14 6:52:17 am GMT-7,BABI,Female,27.0,170.00,65.00,4300.0,5300.0,2. Small Company,No,...,10.00000,2.0,Yes,7.00,7.0,3.0,40.0,Yes,No,2.00
130,2021/09/14 10:06:57 am GMT-7,BABI,Female,36.0,167.00,57.00,7000.0,NaN,1. Large Corporation,No,...,9.00000,3.0,No,7.50,15.0,10.0,40.0,Yes,Yes,1.00
131,2021/09/14 4:54:38 pm GMT-7,BABI,Female,32.0,180.00,54.00,3400.0,4000.0,3. Non-profit or Government Agency,No,...,6.00000,5.0,Yes,7.00,1.0,8.0,35.0,Yes,No,1.00
132,2021/09/14 9:15:48 pm GMT-7,BABI,Female,23.0,165.00,50.00,1000.0,5000.0,4. Other,No,...,5.00000,1.0,No,9.00,20.0,5.0,40.0,Yes,No,1.00
133,2021/09/16 1:54:34 am GMT-7,BABI,Male,25.0,173.00,66.00,4600.0,6600.0,1. Large Corporation,No,...,8.50000,0.0,No,8.00,3.0,20.0,40.0,Yes,Yes,1.00
134,2021/09/16 4:31:13 pm GMT-7,BABI,Male,22.0,182.00,75.00,NaN,NaN,2. Small Company,No,...,10.30000,3.0,No,7.00,20.0,4.0,54.0,Yes,Yes,3.00
135,2021/09/16 5:36:50 pm GMT-7,BABI,Male,31.0,195.58,113.40,5000.0,6500.0,1. Large Corporation,No,...,14.00000,3.0,No,7.00,21.0,14.0,40.0,Yes,Yes,1.00
136,2021/09/16 7:55:58 pm GMT-7,BABI,Female,30.0,163.00,61.00,2800.0,5000.0,1. Large Corporation,No,...,9.50000,0.0,Yes,7.00,8.0,15.0,40.0,Yes,Yes,1.00
137,2022/01/07 1:55:59 pm GMT-8,BITMAN,Male,23.0,180.40,86.18,3800.0,4000.0,2. Small Company,Yes,...,132.00000,2.0,No,8.00,2.0,2.0,NaN,No,No,0.00
138,2022/01/09 10:12:56 pm GMT-8,ITMG,Other,36.0,NaN,NaN,4500.0,5800.0,3. Non-profit or Government Agency,No,...,NaN,7.0,No,8.00,15.0,14.0,5.0,Yes,Yes,2.00

In [10]:
for col in survey.columns:
    #print(type(col))
    print(col+ "hi")

Timestamphi
programhi
Genderhi
Agehi
Heighthi
Weight.hi
Old_Salaryhi
Expected_Salaryhi
Organizationhi
Live_parentshi
Expenseshi
Transportationhi
Transportation_Costhi
Entertainmenthi
Handhi
Cellphone_Costhi
Smokehi
Footsizehi
Alcoholhi
Tattoohi
Sleephi
Social_Networkhi
Homeworkhi
Workhi
Travelhi
Tuitionhi
Coffeehi

In [18]:
##Let's explore a little more:

print(survey.shape)
print("There are ", survey.shape[0]," rows and ",survey.shape[1]," columns")

(139, 27)
There are  139  rows and  27  columns

In [20]:
##lets just look at the first 5 rows:

survey.head(2)

,Timestamp,program,Gender,Age,Height,Weight.,Old_Salary,Expected_Salary,Organization,Live_parents,...,Footsize,Alcohol,Tattoo,Sleep,Social_Network,Homework,Work,Travel,Tuition,Coffee
0,2019/02/04 11:26:35 am GMT-8,HRMG,Female,22.0,177.8,110.0,1400.0,4000.0,3. Non-profit or Government Agency,No,...,11.12,0.0,Yes,8.0,10.0,10.0,0.0,Yes,No,0.0
1,2019/02/04 11:27:45 am GMT-8,HRMG,Female,24.0,175.0,63.0,2000.0,3750.0,2. Small Company,Yes,...,9.50,0.0,Yes,8.0,7.0,20.0,0.0,Yes,Yes,2.0

In [21]:
## or the last 3 rows:
survey.tail(3)

,Timestamp,program,Gender,Age,Height,Weight.,Old_Salary,Expected_Salary,Organization,Live_parents,...,Footsize,Alcohol,Tattoo,Sleep,Social_Network,Homework,Work,Travel,Tuition,Coffee
136,2021/09/16 7:55:58 pm GMT-7,BABI,Female,30.0,163.0,61.00,2800.0,5000.0,1. Large Corporation,No,...,9.5,0.0,Yes,7.0,8.0,15.0,40.0,Yes,Yes,1.0
137,2022/01/07 1:55:59 pm GMT-8,BITMAN,Male,23.0,180.4,86.18,3800.0,4000.0,2. Small Company,Yes,...,132.0,2.0,No,8.0,2.0,2.0,NaN,No,No,0.0
138,2022/01/09 10:12:56 pm GMT-8,ITMG,Other,36.0,NaN,NaN,4500.0,5800.0,3. Non-profit or Government Agency,No,...,NaN,7.0,No,8.0,15.0,14.0,5.0,Yes,Yes,2.0

In [24]:
#To look at just one row:

##survey(2)


## Lets look at only ITMG students 

survey.query("program == 'BABI'")## function attributes

,Timestamp,program,Gender,Age,Height,Weight.,Old_Salary,Expected_Salary,Organization,Live_parents,...,Footsize,Alcohol,Tattoo,Sleep,Social_Network,Homework,Work,Travel,Tuition,Coffee
69,2019/09/09 5:01:07 pm GMT-7,BABI,Female,33.0,167.00,70.0,4000.0,4000.0,1. Large Corporation,No,...,9.68,0.0,No,7.0,1.0,0.0,40.0,No,Yes,0.0
70,2019/09/09 7:14:35 pm GMT-7,BABI,Female,26.0,160.00,50.0,5200.0,NaN,1. Large Corporation,Yes,...,NaN,NaN,No,7.0,15.0,2.0,40.0,Yes,No,0.0
71,2019/09/09 7:14:53 pm GMT-7,BABI,Male,29.0,180.00,65.0,4500.0,7000.0,1. Large Corporation,Yes,...,10.00,0.0,No,7.0,5.0,10.0,40.0,Yes,Yes,3.0
72,2019/09/09 7:15:34 pm GMT-7,BABI,Male,22.0,175.00,59.0,2600.0,3000.0,1. Large Corporation,Yes,...,NaN,3.0,No,8.0,21.0,2.0,40.0,Yes,No,3.0
73,2019/09/09 7:15:42 pm GMT-7,BABI,Female,27.0,166.00,70.0,1600.0,2300.0,3. Non-profit or Government Agency,Yes,...,11.00,0.0,No,7.0,10.0,0.0,40.0,Yes,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,2021/09/14 9:15:48 pm GMT-7,BABI,Female,23.0,165.00,50.0,1000.0,5000.0,4. Other,No,...,5.00,1.0,No,9.0,20.0,5.0,40.0,Yes,No,1.0
133,2021/09/16 1:54:34 am GMT-7,BABI,Male,25.0,173.00,66.0,4600.0,6600.0,1. Large Corporation,No,...,8.50,0.0,No,8.0,3.0,20.0,40.0,Yes,Yes,1.0
134,2021/09/16 4:31:13 pm GMT-7,BABI,Male,22.0,182.00,75.0,NaN,NaN,2. Small Company,No,...,10.30,3.0,No,7.0,20.0,4.0,54.0,Yes,Yes,3.0
135,2021/09/16 5:36:50 pm GMT-7,BABI,Male,31.0,195.58,113.4,5000.0,6500.0,1. Large Corporation,No,...,14.00,3.0,No,7.0,21.0,14.0,40.0,Yes,Yes,1.0
136,2021/09/16 7:55:58 pm GMT-7,BABI,Female,30.0,163.00,61.0,2800.0,5000.0,1. Large Corporation,No,...,9.50,0.0,Yes,7.0,8.0,15.0,40.0,Yes,Yes,1.0

In [20]:
## Or BABI students 

survey.query("program == 'BABI'")

,Timestamp,program,Gender,Age,Height,Weight.,Old_Salary,Expected_Salary,Organization,Live_parents,...,Footsize,Alcohol,Tattoo,Sleep,Social_Network,Homework,Work,Travel,Tuition,Coffee
69,2019/09/09 5:01:07 pm GMT-7,BABI,Female,33.0,167.00,70.0,4000.0,4000.0,1. Large Corporation,No,...,9.68,0.0,No,7.0,1.0,0.0,40.0,No,Yes,0.0
70,2019/09/09 7:14:35 pm GMT-7,BABI,Female,26.0,160.00,50.0,5200.0,NaN,1. Large Corporation,Yes,...,NaN,NaN,No,7.0,15.0,2.0,40.0,Yes,No,0.0
71,2019/09/09 7:14:53 pm GMT-7,BABI,Male,29.0,180.00,65.0,4500.0,7000.0,1. Large Corporation,Yes,...,10.00,0.0,No,7.0,5.0,10.0,40.0,Yes,Yes,3.0
72,2019/09/09 7:15:34 pm GMT-7,BABI,Male,22.0,175.00,59.0,2600.0,3000.0,1. Large Corporation,Yes,...,NaN,3.0,No,8.0,21.0,2.0,40.0,Yes,No,3.0
73,2019/09/09 7:15:42 pm GMT-7,BABI,Female,27.0,166.00,70.0,1600.0,2300.0,3. Non-profit or Government Agency,Yes,...,11.00,0.0,No,7.0,10.0,0.0,40.0,Yes,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,2021/09/14 9:15:48 pm GMT-7,BABI,Female,23.0,165.00,50.0,1000.0,5000.0,4. Other,No,...,5.00,1.0,No,9.0,20.0,5.0,40.0,Yes,No,1.0
133,2021/09/16 1:54:34 am GMT-7,BABI,Male,25.0,173.00,66.0,4600.0,6600.0,1. Large Corporation,No,...,8.50,0.0,No,8.0,3.0,20.0,40.0,Yes,Yes,1.0
134,2021/09/16 4:31:13 pm GMT-7,BABI,Male,22.0,182.00,75.0,NaN,NaN,2. Small Company,No,...,10.30,3.0,No,7.0,20.0,4.0,54.0,Yes,Yes,3.0
135,2021/09/16 5:36:50 pm GMT-7,BABI,Male,31.0,195.58,113.4,5000.0,6500.0,1. Large Corporation,No,...,14.00,3.0,No,7.0,21.0,14.0,40.0,Yes,Yes,1.0
136,2021/09/16 7:55:58 pm GMT-7,BABI,Female,30.0,163.00,61.0,2800.0,5000.0,1. Large Corporation,No,...,9.50,0.0,Yes,7.0,8.0,15.0,40.0,Yes,Yes,1.0

In [21]:
## or students who are over 35:


survey.query("Age >35")

,Timestamp,program,Gender,Age,Height,Weight.,Old_Salary,Expected_Salary,Organization,Live_parents,...,Footsize,Alcohol,Tattoo,Sleep,Social_Network,Homework,Work,Travel,Tuition,Coffee
9,2019/02/04 11:34:05 am GMT-8,HRMG,Male,40.0,185.0,90.0,2000.0,4000.0,1. Large Corporation,No,...,13.0,0.0,Yes,7.0,3.0,14.0,0.0,Yes,No,3.0
12,2019/02/04 11:39:16 am GMT-8,HRMG,Female,38.0,NaN,60.0,3000.0,3500.0,3. Non-profit or Government Agency,No,...,9.0,0.0,No,5.0,14.0,NaN,0.0,Yes,No,0.0
56,2019/02/08 10:42:24 am GMT-8,BMGT,Male,46.0,NaN,90.0,NaN,5000.0,1. Large Corporation,No,...,10.2,3.0,No,7.0,0.0,10.0,0.0,Yes,Yes,3.0
81,2019/09/09 7:17:05 pm GMT-7,BABI,Male,40.0,150.0,70.0,4000.0,8000.0,2. Small Company,No,...,10.0,2.0,Yes,8.0,2.0,0.0,30.0,Yes,Yes,1.0
86,2019/09/09 7:18:59 pm GMT-7,BABI,Male,42.0,178.0,68.0,8000.0,NaN,3. Non-profit or Government Agency,No,...,9.0,0.0,No,7.0,2.0,2.0,40.0,Yes,Yes,2.0
88,2020/08/30 3:50:44 pm GMT-7,BABI,Other,90.0,180.0,70.0,6000.0,7000.0,3. Non-profit or Government Agency,No,...,10.0,4.0,No,7.5,7.0,10.0,32.0,Yes,No,2.0
98,2020/09/14 8:25:19 pm GMT-7,BABI,Female,40.0,165.0,62.0,4000.0,6000.0,1. Large Corporation,No,...,9.0,4.0,Yes,7.0,15.0,0.0,35.0,Yes,Yes,1.0
111,2020/09/15 11:40:49 am GMT-7,BABI,Female,41.0,166.0,78.0,4234.0,6500.0,3. Non-profit or Government Agency,No,...,9.8,3.0,No,7.0,0.0,6.0,35.5,Yes,No,1.0
118,2020/09/28 10:46:56 am GMT-7,BABI,Male,40.0,183.0,86.0,6000.0,6500.0,1. Large Corporation,No,...,10.0,0.0,No,6.0,1.0,25.0,20.0,Yes,Yes,1.0
120,2021/09/08 1:06:36 pm GMT-7,BABI,Female,48.0,155.0,48.0,NaN,NaN,2. Small Company,No,...,9.4,3.0,No,7.0,0.0,NaN,NaN,Yes,Yes,1.0
130,2021/09/14 10:06:57 am GMT-7,BABI,Female,36.0,167.0,57.0,7000.0,NaN,1. Large Corporation,No,...,9.0,3.0,No,7.5,15.0,10.0,40.0,Yes,Yes,1.0
138,2022/01/09 10:12:56 pm GMT-8,ITMG,Other,36.0,NaN,NaN,4500.0,5800.0,3. Non-profit or Government Agency,No,...,NaN,7.0,No,8.0,15.0,14.0,5.0,Yes,Yes,2.0

In [25]:
## Or BABI students who are over 35:


survey.query("program == 'BABI'& Age >35")

,Timestamp,program,Gender,Age,Height,Weight.,Old_Salary,Expected_Salary,Organization,Live_parents,...,Footsize,Alcohol,Tattoo,Sleep,Social_Network,Homework,Work,Travel,Tuition,Coffee
81,2019/09/09 7:17:05 pm GMT-7,BABI,Male,40.0,150.0,70.0,4000.0,8000.0,2. Small Company,No,...,10.0,2.0,Yes,8.0,2.0,0.0,30.0,Yes,Yes,1.0
86,2019/09/09 7:18:59 pm GMT-7,BABI,Male,42.0,178.0,68.0,8000.0,NaN,3. Non-profit or Government Agency,No,...,9.0,0.0,No,7.0,2.0,2.0,40.0,Yes,Yes,2.0
88,2020/08/30 3:50:44 pm GMT-7,BABI,Other,90.0,180.0,70.0,6000.0,7000.0,3. Non-profit or Government Agency,No,...,10.0,4.0,No,7.5,7.0,10.0,32.0,Yes,No,2.0
98,2020/09/14 8:25:19 pm GMT-7,BABI,Female,40.0,165.0,62.0,4000.0,6000.0,1. Large Corporation,No,...,9.0,4.0,Yes,7.0,15.0,0.0,35.0,Yes,Yes,1.0
111,2020/09/15 11:40:49 am GMT-7,BABI,Female,41.0,166.0,78.0,4234.0,6500.0,3. Non-profit or Government Agency,No,...,9.8,3.0,No,7.0,0.0,6.0,35.5,Yes,No,1.0
118,2020/09/28 10:46:56 am GMT-7,BABI,Male,40.0,183.0,86.0,6000.0,6500.0,1. Large Corporation,No,...,10.0,0.0,No,6.0,1.0,25.0,20.0,Yes,Yes,1.0
120,2021/09/08 1:06:36 pm GMT-7,BABI,Female,48.0,155.0,48.0,NaN,NaN,2. Small Company,No,...,9.4,3.0,No,7.0,0.0,NaN,NaN,Yes,Yes,1.0
130,2021/09/14 10:06:57 am GMT-7,BABI,Female,36.0,167.0,57.0,7000.0,NaN,1. Large Corporation,No,...,9.0,3.0,No,7.5,15.0,10.0,40.0,Yes,Yes,1.0

In [26]:
## We can also look at only some columns:
survey['Height']

survey[['program','Age', 'Height']]#.head(3)  # I'm only looking at the first 3

    program   Age  Height
0      HRMG  22.0  177.80
1      HRMG  24.0  175.00
2      HRMG  24.0  182.88
3      HRMG  34.0     NaN
4      HRMG  24.0  160.00
..      ...   ...     ...
134    BABI  22.0  182.00
135    BABI  31.0  195.58
136    BABI  30.0  163.00
137  BITMAN  23.0  180.40
138    ITMG  36.0     NaN

[139 rows x 3 columns]

In [ ]:
## In order to use this with Machine Learning, we'd have to turn it into a numpy array
## but it's cool to look at!